# This file was generated by GoReleaser. DO NOT EDIT.
cask "pi" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_darwin_amd64.tar.gz"
      sha256 "ce25f0f3f89ca708f197db1ed27c6e2c56428273aaf626e78ba545c055e1b7ee"
    end
    on_arm do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_darwin_arm64.tar.gz"
      sha256 "174c17468894fdf0b38e161e8eb6ad9d16fb342b1246e977a387be7a3edda324"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_linux_amd64.tar.gz"
      sha256 "7a2a05817a3cb8df698e608e1bd0f4323c226abf3ad506fce7504f7b83bc4f09"
    end
    on_arm do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_linux_arm64.tar.gz"
      sha256 "ea178ed139ee9736b946dbc23a84f4532b74dd34c4e503621c0860a9aaa13599"
    end
  end

  name "pi"
  desc "Developer automation platform — structured, polyglot, shareable automations"
  homepage "https://github.com/yotam180/pi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pi"]
    end
  end

  # No zap stanza required

end
