# This file was generated by GoReleaser. DO NOT EDIT.
cask "pi" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_darwin_amd64.tar.gz"
      sha256 "de41dfc33140bb98cabf3284c964a9082526773fa5861cbdd15e9ea6564b10b0"
    end
    on_arm do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_darwin_arm64.tar.gz"
      sha256 "adad8d35d07232abe2a3dcf4e87c7201d883fa4b8ac63ef8bd6a69bfbbb78e71"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_linux_amd64.tar.gz"
      sha256 "a42796274cde657d157b8cd0330b602d1617c81cae93fc8499633057c77e17e1"
    end
    on_arm do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_linux_arm64.tar.gz"
      sha256 "539aed214c3ea3e55bd89f398182bb6b0da9fbc75a2e0ba979a1a38abaf66028"
    end
  end

  name "pi"
  desc "Developer automation platform — structured, polyglot, shareable automations"
  homepage "https://github.com/yotam180/pi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pi"]
    end
  end

  # No zap stanza required

end
