# This file was generated by GoReleaser. DO NOT EDIT.
cask "pi" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_darwin_amd64.tar.gz"
      sha256 "600279287157f297e578074bcdb51be4e200da350011a536d591c9c018f6d21c"
    end
    on_arm do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_darwin_arm64.tar.gz"
      sha256 "bba8a3db024fd1b7cd5743a43ca08a976c1eeeb0f38666590cce342ba3551442"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_linux_amd64.tar.gz"
      sha256 "ce0fb1b4c6a5e0e99fd10a1202a6a79596b5c90a2f97572ccd49961f4162a628"
    end
    on_arm do
      url "https://github.com/yotam180/pi/releases/download/v#{version}/pi_#{version}_linux_arm64.tar.gz"
      sha256 "2d2fd305f0efe1568d24b594b8e7b686fff3e955badf0cb9893954b452b13e82"
    end
  end

  name "pi"
  desc "Developer automation platform — structured, polyglot, shareable automations"
  homepage "https://github.com/yotam180/pi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pi"]
    end
  end

  # No zap stanza required

end
